"""
Unit tests for PostgreSQL schema reader.

Tyto testy ověřují správnost mapování PostgreSQL typů na JSON Schema,
detekci auto-generated sloupců a další funkčnost.
"""

import pytest

from TalosForge.db.postgres_schema_reader import PostgresSchemaReader, TYPE_MAP


class TestTypeMapCoverage:
    """Testy pro pokrytí mapování PostgreSQL typů."""

    def test_integer_types_mapped(self):
        """Test, že integer typy jsou mapovány správně."""
        assert TYPE_MAP['integer']['type'] == 'integer'
        assert TYPE_MAP['bigint']['type'] == 'integer'
        assert TYPE_MAP['smallint']['type'] == 'integer'
        assert TYPE_MAP['int2']['type'] == 'integer'
        assert TYPE_MAP['int4']['type'] == 'integer'
        assert TYPE_MAP['int8']['type'] == 'integer'

    def test_numeric_types_mapped(self):
        """Test, že numerické typy jsou mapovány na 'number'."""
        assert TYPE_MAP['numeric']['type'] == 'number'
        assert TYPE_MAP['decimal']['type'] == 'number'
        assert TYPE_MAP['real']['type'] == 'number'
        assert TYPE_MAP['double precision']['type'] == 'number'

    def test_string_types_mapped(self):
        """Test, že string typy jsou mapovány správně."""
        assert TYPE_MAP['varchar']['type'] == 'string'
        assert TYPE_MAP['character varying']['type'] == 'string'
        assert TYPE_MAP['text']['type'] == 'string'

    def test_boolean_type_mapped(self):
        """Test, že boolean typ je mapován správně."""
        assert TYPE_MAP['boolean']['type'] == 'boolean'
        assert TYPE_MAP['bool']['type'] == 'boolean'

    def test_datetime_types_with_format(self):
        """Test, že date/time typy mají správný formát."""
        assert TYPE_MAP['date']['type'] == 'string'
        assert TYPE_MAP['date']['format'] == 'date'

        assert TYPE_MAP['timestamp']['type'] == 'string'
        assert TYPE_MAP['timestamp']['format'] == 'date-time'

        assert TYPE_MAP['timestamptz']['type'] == 'string'
        assert TYPE_MAP['timestamptz']['format'] == 'date-time'

    def test_uuid_type_with_format(self):
        """Test, že UUID typ má správný formát."""
        assert TYPE_MAP['uuid']['type'] == 'string'
        assert TYPE_MAP['uuid']['format'] == 'uuid'

    def test_json_types_mapped(self):
        """Test, že JSON typy jsou mapovány na object."""
        assert TYPE_MAP['json']['type'] == 'object'
        assert TYPE_MAP['jsonb']['type'] == 'object'

    def test_binary_type_with_encoding(self):
        """Test, že binary typ má správné kódování."""
        assert TYPE_MAP['bytea']['type'] == 'string'
        assert TYPE_MAP['bytea']['contentEncoding'] == 'base64'


class TestAutoGeneratedDetection:
    """Testy pro detekci auto-generated sloupců."""

    def test_identity_column_detected(self):
        """Test detekce IDENTITY sloupce."""
        assert PostgresSchemaReader._is_auto_generated(None, 'YES') is True
        assert PostgresSchemaReader._is_auto_generated("some_default", 'YES') is True

    def test_serial_column_detected(self):
        """Test detekce SERIAL sloupce pomocí nextval."""
        assert PostgresSchemaReader._is_auto_generated("nextval('users_id_seq')", 'NO') is True
        assert PostgresSchemaReader._is_auto_generated("nextval('seq')", 'NO') is True

    def test_regular_column_not_detected(self):
        """Test, že běžný sloupec není detekován jako auto-generated."""
        assert PostgresSchemaReader._is_auto_generated(None, 'NO') is False
        assert PostgresSchemaReader._is_auto_generated("'default_value'", 'NO') is False


class TestTypeMapSerialTypes:
    """Testy, že SERIAL typy vrací None (označení jako system-generated)."""

    def test_serial_types_are_none(self):
        """Test, že SERIAL typy vrací None."""
        assert TYPE_MAP.get('serial') is None
        assert TYPE_MAP.get('bigserial') is None


class TestPostgresSchemaReaderInit:
    """Testy pro inicializaci PostgresSchemaReader."""

    def test_init_requires_psycopg2(self, monkeypatch):
        """Test, že inicializace selže bez psycopg2."""
        # Simulace chybějícího psycopg2
        import TalosForge.db.postgres_schema_reader as reader_module
        monkeypatch.setattr(reader_module, 'PSYCOPG2_AVAILABLE', False)

        from TalosForge.core.exceptions import TalosForgeException

        with pytest.raises(TalosForgeException) as exc_info:
            PostgresSchemaReader(
                dsn="host=localhost",
                schema="public",
                table="test"
            )

        assert "psycopg2 is required" in str(exc_info.value)

    def test_init_with_default_values(self):
        """Test inicializace s výchozími hodnotami."""
        if not PostgresSchemaReader.__module__:
            pytest.skip("psycopg2 not available")

        reader = PostgresSchemaReader(
            dsn="host=localhost",
        )
        assert reader.schema == "public"
        assert reader.table == ""
        assert reader.exclude_columns == []


class TestTypeMapEdgeCases:
    """Testy pro okrajové případy v TYPE_MAP."""

    def test_unknown_type_returns_none(self):
        """Test, že neznámý typ vrací None."""
        assert TYPE_MAP.get('unknown_type') is None

    def test_array_types_mapped(self):
        """Test, že array typy jsou mapovány."""
        assert TYPE_MAP.get('array') is not None
        assert TYPE_MAP['array']['type'] == 'array'
        assert TYPE_MAP['_text']['type'] == 'array'
        assert TYPE_MAP['_int4']['type'] == 'array'


class TestColumnDescription:
    """Testy pro přidání description do JSON Schema."""

    def test_description_added_to_schema(self):
        """Test, že description se přidá do JSON Schema když existuje."""
        reader = PostgresSchemaReader(dsn="host=localhost")
        result = reader._map_type_to_json_schema(
            udt_name='varchar',
            column_name='email',
            is_nullable='YES',
            column_default=None,
            is_identity='NO',
            column_description='User email address'
        )
        assert result is not None
        assert result['type'] == 'string'
        assert 'description' in result
        assert result['description'] == 'User email address'

    def test_description_none_omitted(self):
        """Test, že None description se nepřidá do JSON Schema."""
        reader = PostgresSchemaReader(dsn="host=localhost")
        result = reader._map_type_to_json_schema(
            udt_name='varchar',
            column_name='email',
            is_nullable='YES',
            column_default=None,
            is_identity='NO',
            column_description=None
        )
        assert result is not None
        assert result['type'] == 'string'
        assert 'description' not in result

    def test_description_with_auto_generated_column(self):
        """Test, že description se nepřidá pro auto-generated sloupce (vždy readOnly)."""
        reader = PostgresSchemaReader(dsn="host=localhost")
        result = reader._map_type_to_json_schema(
            udt_name='integer',
            column_name='id',
            is_nullable='NO',
            column_default=None,
            is_identity='YES',
            column_description='Unique identifier'
        )
        # Auto-generated sloupce vrací specifický schema bez description
        assert result is not None
        assert result['type'] == 'integer'
        assert result['readOnly'] is True
        assert result['x-system-generated'] is True
        # Description se nepřidává pro auto-generated (můžeme změnit později)

    def test_description_with_integer_type(self):
        """Test, že description funguje pro integer typ."""
        reader = PostgresSchemaReader(dsn="host=localhost")
        result = reader._map_type_to_json_schema(
            udt_name='integer',
            column_name='age',
            is_nullable='YES',
            column_default=None,
            is_identity='NO',
            column_description='User age in years'
        )
        assert result is not None
        assert result['type'] == 'integer'
        assert result['description'] == 'User age in years'


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
